export const ADD_MESSAGE = "ADD_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const ADD_COMMAND = "ADD_COMMAND";
export const AUTHENTICATE = "AUTHENTICATE";

